### ISSUE TITLE
Unable to find LICENSE info

### ISSUE THREAD

**Issue by ghost** [dduong42/hnews#2]
Thanks for publishing this project. Seems interesting but could not find licensing info nor license file.

Request you to please add a license file or licensing info to the primary read me document.

I have submitted a [pull request for a basic readme with licensing](https://github.com/dduong42/hnews/pull/1).

Please consider using 
[Unlicense : Set Your Code Free](http://unlicense.org/)
or
[MIT License](https://en.wikipedia.org/wiki/MIT_License)

Thanks

**Comment by Curti-s** [comment]
A README file is also required. Thanks

**Comment by dduong42** [comment]
@metaprem Merged!
